// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: air_quality.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = System.Collections.Generic;
using grpc = global::Grpc.Core;

namespace HavaDurumu.Integration.Protos
{
    /// <summary>Holder for reflection information generated from air_quality.proto</summary>
    public static partial class AirQualityReflection
    {
        #region Descriptor
        /// <summary>File descriptor for air_quality.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static AirQualityReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChFhaXJfcXVhbGl0eS5wcm90bxINaGF2YV9kdXJ1bXVfMSIoCg9Qb2xs",
                  "dXRpb25SZXF1ZXN0EhkKEHBvbGx1dGlvbl92YWx1ZRgBIAEoASI1ChNB",
                  "aXJRdWFsaXR5UmVzcG9uc2USEAoIbWVzc2FnZRgBIAEoCRIRCglhcWlf",
                  "bGV2ZWwYAiABKAUyYQoRQWlyUXVhbGl0eVNlcnZpY2USYgoVR2V0QWly",
                  "UXVhbGl0eVN0YXR1cxIaLmhhdmFfZHVydW11XzEuUG9sbHV0aW9uUmVx",
                  "dWVzdBogLmhhdmFfZHVydW11XzEuQWlyUXVhbGl0eVJlc3BvbnNlYgZw",
                  "cm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HavaDurumu.Integration.Protos.PollutionRequest), global::HavaDurumu.Integration.Protos.PollutionRequest.Parser, new[]{ "PollutionValue" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HavaDurumu.Integration.Protos.AirQualityResponse), global::HavaDurumu.Integration.Protos.AirQualityResponse.Parser, new[]{ "Message", "AqiLevel" }, null, null, null)
                }));
        }
        #endregion
    }

    #region Messages
    /// <summary>
    /// Kirlilik isteği
    /// </summary>
    public sealed partial class PollutionRequest : pb::IMessage<PollutionRequest>
    {
        private static readonly pb::MessageParser<PollutionRequest> _parser = new pb::MessageParser<PollutionRequest>(() => new PollutionRequest());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<PollutionRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::HavaDurumu.Integration.Protos.AirQualityReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PollutionRequest()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PollutionRequest(PollutionRequest other) : this()
        {
            pollutionValue_ = other.pollutionValue_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PollutionRequest Clone()
        {
            return new PollutionRequest(this);
        }

        /// <summary>Field number for the "pollution_value" field.</summary>
        public const int PollutionValueFieldNumber = 1;
        private double pollutionValue_;
        /// <summary>
        /// PM2.5 değeri
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public double PollutionValue
        {
            get { return pollutionValue_; }
            set
            {
                pollutionValue_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as PollutionRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(PollutionRequest other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PollutionValue, other.PollutionValue))
                return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (PollutionValue != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PollutionValue);
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (PollutionValue != 0D)
            {
                output.WriteRawTag(9);
                output.WriteDouble(PollutionValue);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (PollutionValue != 0D)
            {
                size += 1 + 8;
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(PollutionRequest other)
        {
            if (other == null)
            {
                return;
            }
            if (other.PollutionValue != 0D)
            {
                PollutionValue = other.PollutionValue;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 9:
                        {
                            PollutionValue = input.ReadDouble();
                            break;
                        }
                }
            }
        }
    }

    /// <summary>
    /// Hava kalitesi yanıtı
    /// </summary>
    public sealed partial class AirQualityResponse : pb::IMessage<AirQualityResponse>
    {
        private static readonly pb::MessageParser<AirQualityResponse> _parser = new pb::MessageParser<AirQualityResponse>(() => new AirQualityResponse());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<AirQualityResponse> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::HavaDurumu.Integration.Protos.AirQualityReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AirQualityResponse()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AirQualityResponse(AirQualityResponse other) : this()
        {
            message_ = other.message_;
            aqiLevel_ = other.aqiLevel_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AirQualityResponse Clone()
        {
            return new AirQualityResponse(this);
        }

        /// <summary>Field number for the "message" field.</summary>
        public const int MessageFieldNumber = 1;
        private string message_ = "";
        /// <summary>
        /// Örn: "Hava Kalitesi: SAĞLIKSIZ"
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Message
        {
            get { return message_; }
            set
            {
                message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "aqi_level" field.</summary>
        public const int AqiLevelFieldNumber = 2;
        private int aqiLevel_;
        /// <summary>
        /// AQI seviyesi (1-4)
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int AqiLevel
        {
            get { return aqiLevel_; }
            set
            {
                aqiLevel_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as AirQualityResponse);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(AirQualityResponse other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Message != other.Message) return false;
            if (AqiLevel != other.AqiLevel) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Message.Length != 0) hash ^= Message.GetHashCode();
            if (AqiLevel != 0) hash ^= AqiLevel.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (Message.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Message);
            }
            if (AqiLevel != 0)
            {
                output.WriteRawTag(16);
                output.WriteInt32(AqiLevel);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Message.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
            }
            if (AqiLevel != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(AqiLevel);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(AirQualityResponse other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Message.Length != 0)
            {
                Message = other.Message;
            }
            if (other.AqiLevel != 0)
            {
                AqiLevel = other.AqiLevel;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 10:
                        {
                            Message = input.ReadString();
                            break;
                        }
                    case 16:
                        {
                            AqiLevel = input.ReadInt32();
                            break;
                        }
                }
            }
        }
    }

    #endregion

    #region Services
    /// <summary>
    /// Hava Kalitesi Servisi
    /// </summary>
    public static partial class AirQualityService
    {
        static readonly string __ServiceName = "hava_durumu.AirQualityService";

        /// <summary>Base class for server-side implementations of AirQualityService</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        public abstract partial class AirQualityServiceBase
        {
            /// <summary>
            /// Kirlilik değerine göre hava kalitesi mesajı döndürür
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::System.Threading.Tasks.Task<global::HavaDurumu.Integration.Protos.AirQualityResponse> GetAirQualityStatus(global::HavaDurumu.Integration.Protos.PollutionRequest request, global::Grpc.Core.ServerCallContext context)
            {
                throw new global::System.NotImplementedException();
            }
        }

        /// <summary>Client for AirQualityService</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        public partial class AirQualityServiceClient : global::Grpc.Core.ClientBase<AirQualityServiceClient>
        {
            /// <summary>Creates a new client for AirQualityService</summary>
            /// <param name="channel">The channel to use to make remote calls.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public AirQualityServiceClient(global::Grpc.Core.ChannelBase channel) : base(channel)
            {
            }
            /// <summary>Creates a new client for AirQualityService that uses a custom <c>CallInvoker</c>.</summary>
            /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public AirQualityServiceClient(global::Grpc.Core.CallInvoker callInvoker) : base(callInvoker)
            {
            }
            /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected AirQualityServiceClient() : base()
            {
            }
            /// <summary>Protected constructor to allow creation of configured clients.</summary>
            /// <param name="configuration">The client configuration.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected AirQualityServiceClient(ClientBaseConfiguration configuration) : base(configuration)
            {
            }

            /// <summary>
            /// Kirlilik değerine göre hava kalitesi mesajı döndürür
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::HavaDurumu.Integration.Protos.AirQualityResponse GetAirQualityStatus(global::HavaDurumu.Integration.Protos.PollutionRequest request, global::Grpc.Core.Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return GetAirQualityStatus(request, new global::Grpc.Core.CallOptions(headers, deadline, cancellationToken));
            }
            /// <summary>
            /// Kirlilik değerine göre hava kalitesi mesajı döndürür
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::HavaDurumu.Integration.Protos.AirQualityResponse GetAirQualityStatus(global::HavaDurumu.Integration.Protos.PollutionRequest request, global::Grpc.Core.CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_GetAirQualityStatus, null, options, request);
            }
            /// <summary>
            /// Kirlilik değerine göre hava kalitesi mesajı döndürür
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Grpc.Core.AsyncUnaryCall<global::HavaDurumu.Integration.Protos.AirQualityResponse> GetAirQualityStatusAsync(global::HavaDurumu.Integration.Protos.PollutionRequest request, global::Grpc.Core.Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return GetAirQualityStatusAsync(request, new global::Grpc.Core.CallOptions(headers, deadline, cancellationToken));
            }
            /// <summary>
            /// Kirlilik değerine göre hava kalitesi mesajı döndürür
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Grpc.Core.AsyncUnaryCall<global::HavaDurumu.Integration.Protos.AirQualityResponse> GetAirQualityStatusAsync(global::HavaDurumu.Integration.Protos.PollutionRequest request, global::Grpc.Core.CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_GetAirQualityStatus, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected override AirQualityServiceClient NewInstance(ClientBaseConfiguration configuration)
            {
                return new AirQualityServiceClient(configuration);
            }
        }

        /// <summary>Creates service definition that can be registered with a server</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        public static global::Grpc.Core.ServerServiceDefinition BindService(AirQualityServiceBase serviceImpl)
        {
            return global::Grpc.Core.ServerServiceDefinition.CreateBuilder()
                .AddMethod(__Method_GetAirQualityStatus, serviceImpl.GetAirQualityStatus).Build();
        }

        /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
        /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        public static void BindService(global::Grpc.Core.ServiceBinderBase serviceBinder, AirQualityServiceBase serviceImpl)
        {
            serviceBinder.AddMethod(__Method_GetAirQualityStatus, serviceImpl == null ? null : new global::Grpc.Core.UnaryServerMethod<global::HavaDurumu.Integration.Protos.PollutionRequest, global::HavaDurumu.Integration.Protos.AirQualityResponse>(serviceImpl.GetAirQualityStatus));
        }

        static readonly grpc::Method<global::HavaDurumu.Integration.Protos.PollutionRequest, global::HavaDurumu.Integration.Protos.AirQualityResponse> __Method_GetAirQualityStatus = new grpc::Method<global::HavaDurumu.Integration.Protos.PollutionRequest, global::HavaDurumu.Integration.Protos.AirQualityResponse>(
            grpc::MethodType.Unary,
            __ServiceName,
            "GetAirQualityStatus",
            __Marshaller_PollutionRequest,
            __Marshaller_AirQualityResponse);

        static readonly grpc::Marshaller<global::HavaDurumu.Integration.Protos.PollutionRequest> __Marshaller_PollutionRequest =
            grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::HavaDurumu.Integration.Protos.PollutionRequest.Parser.ParseFrom);
        static readonly grpc::Marshaller<global::HavaDurumu.Integration.Protos.AirQualityResponse> __Marshaller_AirQualityResponse =
            grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::HavaDurumu.Integration.Protos.AirQualityResponse.Parser.ParseFrom);
    }
    #endregion

}
#endregion Designer generated code

